
export const actiontypes={
    FETCH_CATEGORY:"FETCH_CATEGORY",
    ADD_CATEGORY:"ADD_CATEGORY",
    UPDATE_CATEGORY:"UPDATE_CATEGORY",
    FETCH_INCOME:"FETCH_INCOME",
    ADD_INCOME:"ADD_INCOME",
    ADD_EXPENSE:"ADD_EXPENSE",
    DELETE_INCOME:"DELETE_INCOME",
    DELETE_EXPENSE:"DELETE_EXPENSE",
    FETCH_EXPENSE:"FETCH_EXPENSE",
}